# Generated by Django 6.0.1 on 2026-04-10 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 10, 12, 20, 53, 709456, tzinfo=datetime.timezone.utc)),
        ),
    ]
