# Generated by Django 6.0.1 on 2026-07-13 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 13, 12, 12, 37, 220400, tzinfo=datetime.timezone.utc)),
        ),
    ]
