# Generated by Django 6.0.1 on 2026-07-29 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 29, 15, 30, 56, 166278, tzinfo=datetime.timezone.utc)),
        ),
    ]
