# Generated by Django 6.0.1 on 2026-07-29 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 29, 16, 11, 50, 30026, tzinfo=datetime.timezone.utc)),
        ),
    ]
